### ISSUE TITLE
message history not able to push only 1 message

### ISSUE THREAD

**Issue by kenkyusha** [googleapis/python-aiplatform#2875]
In OpenAI chatGPT there is similar feature available i.e. pass in context and also messages plus the last message that came in. Now when I try to do the same thing using vertex AI bison then it fails saying that I cannot have odd number of messages.

The idea is that I already ingest first message from the BOT as starter and then make user to respond to it in order to have 3rd message as response from bot i.e.:
bot: (starts with my pre-written message in history)
user: (my current response)
bot: (newly generated message)

```
*** google.api_core.exceptions.InvalidArgument: 400 There should be odd number of messages for correct alternating turn.
```

#### Environment details

  - OS type and version: macOS m1
  - Python version: python3.10
  - pip version: `pip --version`
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform`

#### Steps to reproduce

  1. Run the same code, the idea is that message_history should be possible to only have 1 message from BOT (i.e. the bot started conversation and now I passed it down to it as extra knowledge).
  2. Currently this yields: an error ```***** google.api_core.exceptions.InvalidArgument: 400 There should be odd number of messages for correct alternating turn.**```
  3. 

#### Code example

```python
import vertexai
from vertexai.preview.language_models import ChatModel, InputOutputTextPair, ChatMessage

chat_model = ChatModel.from_pretrained("chat-bison@001")
parameters = {
    "temperature": 0.7,  
    "max_output_tokens": 256, 
    "top_p": 0.95, 
    "top_k": 40,  
}

def call_bison(ctx, message_log, user_msg):
    chat = chat_model.start_chat(
        context=ctx,
        message_history = message_log,
    )
    response = chat.send_message(
        user_msg, **parameters
    )   
    return response.text

ctx = "Act as BobCat"
log = [ChatMessage(content='Hello, I am a BobCat ?', author='bot'), ChatMessage(content='Hey BobCat what can you do for me ?', author='user')]

call_bison(ctx=ctx, message_log=log[:-1], user_msg=log[-1].content)

```

#### Stack trace
```
google.api_core.exceptions.InvalidArgument: 400 There should be odd number of messages for correct alternating turn.
```

**Comment by Ark-kun** [comment]
Can you please help me better understand your use case.
It looks like you're trying to send to the model a list of messages that ends with the bot message. I'm not sure this is semantically correct. The message sent to the model should come from a user. A model cannot respond to the user is the user does not ask anything. Also, the model cannot really initiate the conversation with the user since the model only reacts to the user messages.

Can you please share a minimal example of the full input list of messages and the expected model output.

**Comment by kenkyusha** [comment]
Essentially when I give the model some context and I want it to start with specific sentence (i.e. they start by saying something). Then I want to be able to set this message myself... i.e. I want the bot to start with saying:
"'Hello, I am a BobCat" -> now I do not need to prompt it in OAI chatGPT, I could already say it has been said and now the following messages from user:
"Hey BobCat what can you do for me ?" -> this is now passed in as user_msg where as the first bot message is in the message_history.

So that the message is from the user as you can see from the code (author = "user") and the message_history is a list with only one message from the bot.

**Comment by bonadio** [comment]
Hi, I have the same problem. I want the model to start asking the user. 
I am creating a bot for a pizzeria. When the user finish his food order I want the bot to ask for the payment method.
I need to model to start asking "How would you like to pay? Card or Money"

`import vertexai
from vertexai.language_models import ChatModel, InputOutputTextPair, ChatMessage

vertexai.init(project="***", location="us-central1")
chat_model = ChatModel.from_pretrained("chat-bison")
parameters = {
    "candidate_count": 1,
    "max_output_tokens": 1024,
    "temperature": 0,
    "top_p": 0.8,
    "top_k": 40
}

messages_history = [
    ChatMessage(author="AI", content="How would you like to pay? Card or Money?")
]

chat = chat_model.start_chat(
    context="""You are a customer service chatbot for a pizzeria.
You must collect the payment information. The payment options are: \"card\" debit or credit,  or money. If the customer choose money, you need to ask he needs change and the amount.
You only answer customer questions about payment at the pizzeria.
""",
    examples=[
        InputOutputTextPair(
            input_text="""money""",
            output_text="""Do you need change?"""
        )
    ],
    message_history=messages_history
)
response = chat.send_message("""I will pay with money""", **parameters)
print(f"Response from Model: {response.text}")`

**Comment by Ark-kun** [comment]
The error message seems to be pretty clear:
`InvalidArgument: 400 There should be odd number of messages for correct alternating turn.`

When you have:

```python
messages_history = [
    ChatMessage(author="User", content="Hi")
    ChatMessage(author="AI", content="How would you like to pay? Card or Money?")
]
chat = chat_model.start_chat(message_history=messages_history)
chat.send_message("""I will pay with money""", **parameters)
```

you have "odd number of messages (3) in alternating turns".

If you remove the first user message from history, then it's no longer true.


>I just found out that if you add an initial "user" message with "Hi" it works, it's a hack

I'm not sure it's a hack. It's how it's supposed to be. The user always initiates the conversation with the model in one way or another, and the model always reacts. 

>I want the bot to start with saying: "'Hello, I am a BobCat"

Note that the ChatModel and ChatSession classes are not a bot app. They are the foundation of the bot app that you build on top. 
Since in reality only user can initiate a conversation (model does not just randomly decides to call my phone at 2AM), you need to initialize history with request-response pairs. For example:
>User: "Hello"
>Model: "Hello, I am a BobCat"

Then you send the message you've received from the user.
>User: "Hey BobCat what can you do for me ?

**Comment by Kaskyi** [comment]
I don't understand why I should put a mock user message (Hi) just to make your API work. 
workaround:
```python
if len(message_history) % 2:
    message_history.insert(0, ChatMessage('start', 'user'))
```
