### ISSUE TITLE
Pipeline root can not be bucket root after change in storage API

### ISSUE THREAD

**Issue by mcompen** [googleapis/python-aiplatform#2936]
#### Environment details

  - All OS and Python versions:
  - google-cloud-storage==2.13.0

#### Code example

```python
job = aip.PipelineJob(
               ...
                pipeline_root="gs://bucket_root",  # note no trailing slash and no blob provided
               ...
            )
```

#### Stack trace
```
"/Users/manu.compen/Library/Caches/pypoetry/virtualenvs/bla-py3.9/lib/python3.9/site-packages/google/cloud/aiplatform/pipeline_jobs.py", line 404, in submit
    gcs_utils.create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist(
  File "/Users/manu.compen/Library/Caches/pypoetry/virtualenvs/bla-py3.9/lib/python3.9/site-packages/google/cloud/aiplatform/utils/gcs_utils.py", line 237, in create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist
    pipelines_bucket = storage.Blob.from_string(
  File "/Users/manu.compen/Library/Caches/pypoetry/virtualenvs/bla-py3.9/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 410, in from_string
    raise ValueError("URI scheme must be gs")
ValueError: URI scheme must be gs
```

See change in python-storage `Blob` api:  https://github.com/googleapis/python-storage/commit/0a243faf5d6ca89b977ea1cf543356e0dd04df95

**Comment by Yashikab** [comment]
After reviewing the source code, 
it appears that the issue lies within the `create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist` function in [utils/gs_utils.py](https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/utils/gcs_utils.py#L194C5-L267) where the bucket is retrieved. 
The problem seems to stem from using Blob.from_string to obtain the URI and then converting it to a bucket.
(https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/utils/gcs_utils.py#L237-L240)

To resolve this, replacing Blob.from_string with [Bucket.from_string](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.bucket.Bucket#google_cloud_storage_bucket_Bucket_from_string) after extracting bucket path from `output_artifacts_gcs_dir` should fix the issue.
