### ISSUE TITLE
ResponseBlockedError is not exported from vertexai.generative_models

### ISSUE THREAD

**Issue by sebastiancarlsson** [googleapis/python-aiplatform#3375]
With version 1.42.0, [GenerativeModel was released to GA](https://github.com/googleapis/python-aiplatform/blob/main/CHANGELOG.md#1420-2024-02-15) ([c7e3f07](https://github.com/googleapis/python-aiplatform/commit/c7e3f076f91f002ac5a889d8942a153e57e0147c))

After I installed this update, I went through my code and removed the `preview` part of the import statements, but noticed that `ResponseBlockedError` could not be found in the new package. It seems that this class is not exported from `vertexai.generative_models`.

I would like to contribute a fix myself but can't because of legal reasons (waiting for the contributor agreement to be approved by my company). As far as I can see the fix is as simple as adding `ResponseBlockedError` to`vertexai/generative_models/__init__.py` (the class is defined in `vertexai/generative_models/_generative_models.py`).

#### Environment details
  - `google-cloud-aiplatform` version:  1.42.1

#### Code example

This (still) works:
```python
from vertexai.preview.generative_models import ResponseBlockedError
```

This doesn't work:
```python
from vertexai.generative_models import ResponseBlockedError
```

**Comment by Ark-kun** [comment]
Would it be OK for you o switch to `ResponseValidationError`?
```
from vertexai.generative_models import  ResponseValidationError
```
The new exception name better represent what happens.

P.S. What is your opinion on these exceptions? Are they annoying or useful? I tried my best to make sure that `ChatSession` cannot get into unusable state (which can happen if blocked or incomplete responses are added to chat message history).

P.P.S. What's your opinion on raising exception on the response going over max_tokens? In this case the model response is essentially cut-off and incomplete, which is why we're raising error rather than adding it to history automatically.

**Comment by sebastiancarlsson** [comment]
Thank you for the input @Ark-kun. If I'm not mistaken the ChatSession still raises the `ResponseBlockedError`, it's just not exposed in a way that I can import it. At the moment my workaround is this:
```
from vertexai.generative_models._generative_models import ResponseBlockedError
```
But if you are planning to change this to use `ResponseValidationError` that's fine and semantically it makes more sense like you say.

I think that these exceptions are both good and useful, it's important that the api deals with this in a way so that a chat session doesn't need to be restarted so the current functionality is great. I haven't encountered the max tokens exception as I'm working with quite small prompts/answers but I think it's fair to raise an exception in this case too.
