### ISSUE TITLE
Add support to pass metadata from GenerativeModel.generate_content and Chat:send_message

### ISSUE THREAD

**Issue by vi3k6i5** [googleapis/python-aiplatform#3490]
Currently we cant pass additional headers to VertexAI which might be needed for proxy.

Example:
```
client = GenerativeModel("gemini-pro")
metadata = (("x-header-key", "value"),) # Currently not supported.
client.generate_content("Give me a random fun fact", metadata=metadata)
```

**Comment by Ark-kun** [comment]
I think this feature is pretty generic, global and not quite related to `generate_content`. The `generate_content` is a high-level function that is high-above the HTTP level. In fact for most users it does not use HTTP since it uses GRPC. (Note that streaming is not supported over HTTP.)

Having said that, this feature would probably be better implemented as a context manager that globally adds a value to metadata.

Are you sure that the requests will work through proxy if metadata is added?

**Comment by vi3k6i5** [comment]
Hi @Ark-kun The goal is to be able to send additional headers for any http rest request that Vetex makes. This will help the proxy server with some validations.

> Having said that, this feature would probably be better implemented as a context manager that globally adds a value to metadata.

So if this is implemented it will help. We don't necessarily need the metadata support at generate_content.

Similar request is this one as well : https://github.com/googleapis/python-aiplatform/issues/3526 

Basically any way to pass custom headers, If it's metadata or some other way to specify headers when we do vertex init.

**Comment by Ark-kun** [comment]
This feature has been implemented and released. It's now possible to globally set additional metadata taht will be set with all requests.

Usage:

```
vertexai.init(request_metadata=[("key1", "value1")])
```
