### ISSUE TITLE
Extend Type Hint for the content Parameter of send_message Functions Generative Models

### ISSUE THREAD

**Issue by luxzoli** [googleapis/python-aiplatform#3958]
**Is your feature request related to a problem? Please describe.**

The [content parameter of the send_message](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/generative_models/_generative_models.py#L891) and similar functions does not imply with the type hint that it accepts Content objects as well (defined in the same file).

 **Describe the solution you'd like**

Extend the type hint and documentation for the content variable of the affected functions.

 **Describe alternatives you've considered**

None

 **Additional context**

I can prepare a PR for this change if desired

**Comment by Ark-kun** [comment]
Hello. We do not officially support taking `Content` objects in `ChatSession.send_message`, so the type hint is correct and intentional.

The rationale is: `Content` = `parts`+`role`. `role` is managed by `ChatSession`. This leaves `parts`. So `send_message` essentially takes a list of parts. A `PartsType`.

If you want to send manually-crafted `Content` objects to the model, consider using `GenerativeModel.generate_content`.

Does this make sense?

**Comment by luxzoli** [comment]
@Ark-kun Yes, thanks for the feedback. A clear and easy way could then be to use the `parts` attribute of the manually crafted `Content` object, which is a list of parts. By the way, the code to be adjusted is [here in Microsoft Autogen](https://github.com/microsoft/autogen/blob/20f8ba9cfae4a3c70c3131d4f14bf14ba4dc5ced/autogen/oai/gemini.py#L197)
