### ISSUE TITLE
Samples should provide instructions for users on how to set variables. 

### ISSUE THREAD

**Issue by sgreenberg** [googleapis/python-aiplatform#57]
Raising this issue because I saw @kurtisvg 's comment in https://github.com/googleapis/python-aiplatform/pull/13. 

A snippet like https://github.com/googleapis/python-aiplatform/blob/sample-final-stage/samples/snippets/get_model_evaluation_video_classification_sample.py as one example, does not provide the user instructions on what a valid value for `project`,  `model_id`, or `evaluation_id` should look like. That's something we should fix. 

Kurtis brings up two ideas - one is adding comments, the other is adding a `run_sample()` wrapper function. Both are valid ideas - and I want the team to make the choice here. My personal opinion is that comments work better in the python ecosystem. But again, happy to let the team decide.

I want to make sure the solution is one that we can scalably roll out across all ~100 of our samples. So I want the change to be made in the generator rather than as one-offs in changes to already-generated samples.

**Comment by kurtisvg** [comment]
The reason we've moved from suggesting comments to the wrapper function instead is that comments aren't linted (either for style, for type, or for language correctness). This has lead to situations where the comments end up being incorrect (when a function signature changed or something else and the comments weren't updated), which is why the wrapper function is preferred.

**Comment by ivanmkc** [comment]
What would a wrapper function look like and how it improve the understanding of valid values without comments of its own?

**Comment by andrewferlitsch** [comment]
per team discussion, closing.
